import { Capacitor } from "@capacitor/core";

/**
 * Edge-level anti-spoofing (Quadrant I requirement).
 *
 * ===========================================================================
 * PLATFORM REALITY — READ BEFORE RELYING ON THIS FOR FRAUD PREVENTION
 * ===========================================================================
 *
 * ANDROID — genuinely effective.
 *   `capacitor-mock-location-checker` runs native routines that evaluate
 *   Location.isMock() / isFromMockProvider() and additionally enumerate
 *   installed apps holding the mock-location permission. This reliably
 *   catches the "Fake GPS"-class apps the blueprint is concerned about.
 *
 * iOS — MUCH WEAKER THAN THE BLUEPRINT ASSUMES.
 *   The blueprint states the iOS equivalent (`isSimulatedBySoftware`) should
 *   be "aggressively audited". That property does exist (CLLocation
 *   .sourceInformation, iOS 15+) — an earlier revision of this client
 *   incorrectly claimed iOS had no equivalent at all, and that was wrong.
 *
 *   However, Apple engineers have confirmed on the developer forums that the
 *   flag is only set for locations generated by Core Location's OWN
 *   simulation (i.e. Xcode's Debug > Simulate Location / GPX injection). The
 *   commercial desktop spoofing tools an employee would realistically use
 *   (LocaChange, iTool AnyTo, and similar) inject location outside Core
 *   Location's simulation path and are reported to leave the flag FALSE on
 *   current iOS versions.
 *
 *   There is also an implementation trap: the flag is only populated on
 *   CLLocation objects delivered through the didUpdateLocations delegate
 *   callback. Reading CLLocationManager().location directly returns a
 *   location whose sourceInformation is nil/false even when simulation is
 *   active.
 *
 *   NET EFFECT: iOS check-in spoofing is NOT reliably preventable at the
 *   client. Do not present iOS anti-spoofing as equivalent to Android to HR
 *   or in the project report. The compensating controls are server-side and
 *   belong to Person 3 / Person 4 — see the note at the bottom of this file.
 * ===========================================================================
 */

// Apps that legitimately hold mock-location permission on some OEM ROMs and
// would otherwise cause false-positive lockouts for honest employees.
const DEFAULT_WHITELIST = [];

/**
 * @returns {Promise<{isMock: boolean, confidence: 'reliable'|'weak'|'unavailable',
 *                    platform: string, indicatedApps: string[], messages: string[]}>}
 */
export async function checkMockLocation(whiteList = DEFAULT_WHITELIST) {
  const platform = Capacitor.getPlatform();

  if (platform === "web") {
    // Browser dev builds have no native bridge. Fail OPEN here (dev
    // convenience) but the server re-checks regardless, and production
    // builds never run on the web platform.
    return {
      isMock: false,
      confidence: "unavailable",
      platform,
      indicatedApps: [],
      messages: ["Mock-location checking is unavailable in the browser dev build."],
    };
  }

  try {
    const { MockLocationChecker } = await import("capacitor-mock-location-checker");
    const result = await MockLocationChecker.checkMock({ whiteList });

    return {
      isMock: !!result?.isMock,
      // Honest confidence labelling — the UI and the anomaly report both
      // carry this so nobody downstream mistakes an iOS "clean" result for
      // a strong guarantee.
      confidence: platform === "android" ? "reliable" : "weak",
      platform,
      indicatedApps: Array.isArray(result?.indicated) ? result.indicated : [],
      messages: Array.isArray(result?.messages) ? result.messages : [],
    };
  } catch (err) {
    // Plugin missing or native call failed. FAIL CLOSED for the check-in
    // decision: treat an unknown spoofing state on a real device as
    // suspicious rather than waving it through.
    return {
      isMock: true,
      confidence: "unavailable",
      platform,
      indicatedApps: [],
      messages: [`Mock-location check could not run: ${err?.message ?? "unknown error"}`],
    };
  }
}

/**
 * SERVER-SIDE COMPENSATING CONTROLS (for Person 3 / Person 4, not implemented
 * here — recorded so the gap above is not silently accepted):
 *
 *  1. Impossible-travel detection: reject/flag a check-in whose coordinates
 *     imply a physically impossible speed since the employee's previous
 *     attendance log. This catches spoofing regardless of platform and is
 *     the single highest-value backend mitigation.
 *  2. Cross-signal correlation: compare GPS against the device's IP
 *     geolocation at the API edge; a Dhaka office coordinate arriving from a
 *     residential IP 20km away is a strong anomaly signal.
 *  3. Device binding: bind check-ins to a registered device identifier so a
 *     spoofed location from an unrecognised device is flagged.
 *  4. Face-match remains the true backstop — spoofed GPS still cannot
 *     produce the correct live face.
 */
